// Each template is genuinely distinct in layout logic, not just recolored.
export const TEMPLATES = [
  {
    id: 'modern',
    name: 'Modern',
    style: 'Modern',
    columns: 2,
    hasPhoto: true,
    photoShape: 'circle',
    icon: 'PanelLeft',
    description: 'Sidebar with photo + contact, bold sans headline on the main column.',
    defaultColor: '#B4813F',
  },
  {
    id: 'minimal',
    name: 'Minimal',
    style: 'Minimal',
    columns: 1,
    hasPhoto: false,
    photoShape: 'none',
    icon: 'Minus',
    description: 'Single column, generous whitespace, understated rule-based dividers.',
    defaultColor: '#14181D',
  },
  {
    id: 'harvard',
    name: 'Harvard',
    style: 'ATS Friendly',
    columns: 1,
    hasPhoto: false,
    photoShape: 'none',
    icon: 'GraduationCap',
    description: 'Classic academic CV format. Centered header, serif, ATS-safe.',
    defaultColor: '#14181D',
  },
  {
    id: 'executive',
    name: 'Executive',
    style: 'Executive',
    columns: 1,
    hasPhoto: false,
    photoShape: 'none',
    icon: 'Landmark',
    description: 'Wide letterhead-style header with a rule, confident serif display type.',
    defaultColor: '#2E4057',
  },
  {
    id: 'dark',
    name: 'Dark Slate',
    style: 'Dark',
    columns: 2,
    hasPhoto: true,
    photoShape: 'square',
    icon: 'Moon',
    description: 'Dark sidebar, high-contrast, tech-forward.',
    defaultColor: '#7BD1C8',
  },
  {
    id: 'designer',
    name: 'Designer',
    style: 'Creative',
    columns: 2,
    hasPhoto: true,
    photoShape: 'circle',
    icon: 'PenTool',
    description: 'Asymmetric layout with a color block header and diagonal accent.',
    defaultColor: '#C24C4C',
  },
  {
    id: 'timeline',
    name: 'Timeline',
    style: 'Timeline',
    columns: 1,
    hasPhoto: true,
    photoShape: 'circle',
    icon: 'Milestone',
    description: 'Experience rendered as a vertical connected timeline.',
    defaultColor: '#3E8F63',
  },
  {
    id: 'twocolumn',
    name: 'Two Column Tech',
    style: 'Software Engineer',
    columns: 2,
    hasPhoto: false,
    photoShape: 'none',
    icon: 'Code2',
    description: 'Monospace accents, skills-first layout built for engineering roles.',
    defaultColor: '#2954E5',
  },
  {
    id: 'corporate',
    name: 'Corporate',
    style: 'Corporate',
    columns: 2,
    hasPhoto: false,
    photoShape: 'none',
    icon: 'Building2',
    description: 'Full-width letterhead bar, formal two-column body, contact-only sidebar.',
    defaultColor: '#B4813F',
  },
  {
    id: 'contemporary',
    name: 'Contemporary',
    style: 'Contemporary',
    columns: 2,
    hasPhoto: true,
    photoShape: 'circle',
    icon: 'Layers',
    description: 'Centered banner header, mirrored right-hand sidebar, bold underline headings.',
    defaultColor: '#C24C4C',
  },
  {
    id: 'compactats',
    name: 'Compact ATS',
    style: 'ATS Friendly',
    columns: 1,
    hasPhoto: false,
    photoShape: 'none',
    icon: 'ListChecks',
    description: 'Dense, plain, parser-safe single column with minimal styling.',
    defaultColor: '#14181D',
  },
  {
    id: 'student',
    name: 'Student',
    style: 'Student',
    columns: 1,
    hasPhoto: true,
    photoShape: 'square',
    icon: 'BookOpen',
    description: 'Education-first ordering, rounded friendly accents, small photo.',
    defaultColor: '#3E8F63',
  },
  {
    id: 'elegant',
    name: 'Elegant',
    style: 'Elegant',
    columns: 1,
    hasPhoto: true,
    photoShape: 'circle',
    icon: 'Sparkles',
    description: 'Centered layout, italic serif accents, ornamental section dividers.',
    defaultColor: '#8A6D3B',
  },
  {
    id: 'gridcards',
    name: 'Grid Cards',
    style: 'Creative',
    columns: 2,
    hasPhoto: true,
    photoShape: 'square',
    icon: 'LayoutGrid',
    description: 'Sections as bordered masonry cards — wide cards for experience, compact for the rest.',
    defaultColor: '#2954E5',
  },
  {
    id: 'portrait',
    name: 'Portrait',
    style: 'Professional',
    columns: 1,
    hasPhoto: true,
    photoShape: 'circle',
    icon: 'CircleUserRound',
    description: 'Large centered portrait photo, clean single column, confident and professional.',
    defaultColor: '#B4813F',
  },
  {
    id: 'magazine',
    name: 'Magazine',
    style: 'Creative',
    columns: 2,
    hasPhoto: true,
    photoShape: 'square',
    icon: 'GalleryVerticalEnd',
    description: 'Full-bleed photo panel down the side with your name overlaid, editorial feel.',
    defaultColor: '#2E4057',
  },
  {
    id: 'coverbanner',
    name: 'Cover Banner',
    style: 'Professional',
    columns: 2,
    hasPhoto: true,
    photoShape: 'square',
    icon: 'Image',
    description: 'Wide color banner header with a prominent framed photo, two-column body.',
    defaultColor: '#8A6D3B',
  },
  {
    id: 'executiveframe',
    name: 'Executive Frame',
    style: 'Executive',
    columns: 1,
    hasPhoto: true,
    photoShape: 'square',
    icon: 'Frame',
    description: 'Formal letterhead layout with a framed portrait, understated and corporate.',
    defaultColor: '#2E4057',
  },
];

export const TEMPLATE_STYLES = [...new Set(TEMPLATES.map((t) => t.style))];
